spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/full_stack_ecommerce
    username: ecom
    password: ecom
  jpa:
    show-sql: true
    properties:
      hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    rest:
      base-path: /api